using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OneBusAway
{
    public class Mapping
    {
        public string university__of__washington { get; set; }
        public string passenger__terminal { get; set; }
        public string convention__place { get; set; }
        public string downtown__seattle { get; set; }
        public string east__green__lake { get; set; }
        public string link__light__rail { get; set; }
        public string ferry__terminal { get; set; }
        public string medical__center { get; set; }
        public string point__defiance { get; set; }
        public string transit__center { get; set; }
        public string downtown__only { get; set; }
        public string international { get; set; }
        public string park__and__ride { get; set; }
        public string port__townsend { get; set; }
        public string all__stations { get; set; }
        public string capitol__hill { get; set; }
        public string high__school { get; set; }
        public string laurelhurst { get; set; }
        public string mount__baker { get; set; }
        public string park____ride { get; set; }
        public string the__landing { get; set; }
        public string wallingford { get; set; }
        public string circulator { get; set; }
        public string crossroads { get; set; }
        public string fauntleroy { get; set; }
        public string northbound { get; set; }
        public string queen__anne { get; set; }
        public string snoqualmie { get; set; }
        public string southbound { get; set; }
        public string steilacoom { get; set; }
        public string university { get; set; }
        public string alderwood { get; set; }
        public string anacortes { get; set; }
        public string arlington { get; set; }
        public string boulevard { get; set; }
        public string bremerton { get; set; }
        public string brickyard { get; set; }
        public string community { get; set; }
        public string connector { get; set; }
        public string chinatown { get; set; }
        public string dwntn__tac { get; set; }
        public string education { get; set; }
        public string jefferson { get; set; }
        public string kennydale { get; set; }
        public string roosevelt { get; set; }
        public string sheridian { get; set; }
        public string shoreline { get; set; }
        public string tahlequah { get; set; }
        public string airfield { get; set; }
        public string bellevue { get; set; }
        public string broadway { get; set; }
        public string cascadia { get; set; }
        public string commerce { get; set; }
        public string connecto { get; set; }
        public string district { get; set; }
        public string downtown { get; set; }
        public string enumclaw { get; set; }
        public string exchange { get; set; }
        public string factoria { get; set; }
        public string fairview { get; set; }
        public string fairwood { get; set; }
        public string hospital { get; set; }
        public string houghton { get; set; }
        public string issaquah { get; set; }
        public string junction { get; set; }
        public string kathleen { get; set; }
        public string kingston { get; set; }
        public string kirkland { get; set; }
        public string lynnwood { get; set; }
        public string magnolia { get; set; }
        public string magnuson { get; set; }
        public string mckinley { get; set; }
        public string meridian { get; set; }
        public string military { get; set; }
        public string mt__baker { get; set; }
        public string mukilteo { get; set; }
        public string outbound { get; set; }
        public string prentice { get; set; }
        public string puyallup { get; set; }
        public string richmond { get; set; }
        public string stanwood { get; set; }
        public string admiral { get; set; }
        public string airport { get; set; }
        public string ballard { get; set; }
        public string bothell { get; set; }
        public string carkeek { get; set; }
        public string central { get; set; }
        public string college { get; set; }
        public string commons { get; set; }
        public string diamond { get; set; }
        public string edmonds { get; set; }
        public string everett { get; set; }
        public string express { get; set; }
        public string federal { get; set; }
        public string fremont { get; set; }
        public string granite { get; set; }
        public string gregory { get; set; }
        public string heights { get; set; }
        public string inbound { get; set; }
        public string jackson { get; set; }
        public string juanita { get; set; }
        public string judkins { get; set; }
        public string kenmore { get; set; }
        public string kinnear { get; set; }
        public string landing { get; set; }
        public string madigan { get; set; }
        public string madison { get; set; }
        public string madrona { get; set; }
        public string mariner { get; set; }
        public string olympia { get; set; }
        public string othello { get; set; }
        public string rainier { get; set; }
        public string ravenna { get; set; }
        public string redmond { get; set; }
        public string pacific { get; set; }
        public string pioneer { get; set; }
        public string proctor { get; set; }
        public string redondo { get; set; }
        public string sea__tac { get; set; }
        public string sea_tac { get; set; }
        public string seattle { get; set; }
        public string shuttle { get; set; }
        public string sounder { get; set; }
        public string special { get; set; }
        public string station { get; set; }
        public string stevens { get; set; }
        public string terrace { get; set; }
        public string theater { get; set; }
        public string transit { get; set; }
        public string tukwila { get; set; }
        public string tulalip { get; set; }
        public string up_town { get; set; }
        public string village { get; set; }
        public string warrior { get; set; }
        public string alaska { get; set; }
        public string auburn { get; set; }
        public string aurora { get; set; }
        public string beacon { get; set; }
        public string benson { get; set; }
        public string boeing { get; set; }
        public string bridge { get; set; }
        public string burien { get; set; }
        public string burton { get; set; }
        public string canyon { get; set; }
        public string casino { get; set; }
        public string center { get; set; }
        public string cherry { get; set; }
        public string church { get; set; }
        public string colman { get; set; }
        public string duvall { get; set; }
        public string fedway { get; set; }
        public string friday { get; set; }
        public string george { get; set; }
        public string haller { get; set; }
        public string harbor { get; set; }
        public string island { get; set; }
        public string mercer { get; set; }
        public string milton { get; set; }
        public string mirror { get; set; }
        public string monroe { get; set; }
        public string pierce { get; set; }
        public string purple { get; set; }
        public string renton { get; set; }
        public string seatac { get; set; }
        public string seward { get; set; }
        public string silver { get; set; }
        public string smokey { get; set; }
        public string square { get; set; }
        public string street { get; set; }
        public string summit { get; set; }
        public string tacoma { get; set; }
        public string timber { get; set; }
        public string uptown { get; set; }
        public string valley { get; set; }
        public string vashon { get; set; }
        public string woodin { get; set; }
        public string yakima { get; set; }
        public string yesler { get; set; }
        public string angle { get; set; }
        public string arbor { get; set; }
        public string beach { get; set; }
        public string black { get; set; }
        public string clyde { get; set; }
        public string coupe { get; set; }
        public string creek { get; set; }
        public string crest { get; set; }
        public string falls { get; set; }
        public string first { get; set; }
        public string green { get; set; }
        public string inter { get; set; }
        public string kings { get; set; }
        public string lakes { get; set; }
        public string lands { get; set; }
        public string lewis { get; set; }
        public string lopez { get; set; }
        public string lower { get; set; }
        public string loyal { get; set; }
        public string maple { get; set; }
        public string marys { get; set; }
        public string mount { get; set; }
        public string north { get; set; }
        public string orcas { get; set; }
        public string pearl { get; set; }
        public string point { get; set; }
        public string purdy { get; set; }
        public string ridge { get; set; }
        public string river { get; set; }
        public string shore { get; set; }
        public string south { get; set; }
        public string super { get; set; }
        public string swamp { get; set; }
        public string swift { get; set; }
        public string totem { get; set; }
        public string union { get; set; }
        public string ville { get; set; }
        public string white { get; set; }
        public string worth { get; set; }
        public string army { get; set; }
        public string bain { get; set; }
        public string bear { get; set; }
        public string bend { get; set; }
        public string blue { get; set; }
        public string city { get; set; }
        public string coll { get; set; }
        public string dash { get; set; }
        public string dock { get; set; }
        public string dome { get; set; }
        public string down { get; set; }
        public string dtwn { get; set; }
        public string dwtn { get; set; }
        public string east { get; set; }
        public string ever { get; set; }
        public string fair { get; set; }
        public string firs { get; set; }
        public string gate { get; set; }
        public string gold { get; set; }
        public string high { get; set; }
        public string hill { get; set; }
        public string hoyt { get; set; }
        public string kent { get; set; }
        public string king { get; set; }
        public string lake { get; set; }
        public string land { get; set; }
        public string leaf { get; set; }
        public string line { get; set; }
        public string link { get; set; }
        public string loop { get; set; }
        public string main { get; set; }
        public string mall { get; set; }
        public string mont { get; set; }
        public string over { get; set; }
        public string park { get; set; }
        public string pike { get; set; }
        public string port { get; set; }
        public string post { get; set; }
        public string shaw { get; set; }
        public string tech { get; set; }
        public string town { get; set; }
        public string road { get; set; }
        public string sand { get; set; }
        public string star { get; set; }
        public string stcr { get; set; }
        public string twin { get; set; }
        public string vasa { get; set; }
        public string wedg { get; set; }
        public string west { get; set; }
        public string wood { get; set; }
        public string zone { get; set; }
        public string and { get; set; }
        public string ash { get; set; }
        public string ave { get; set; }
        public string bar { get; set; }
        public string fhs { get; set; }
        public string gig { get; set; }
        public string pr { get; set; }
        public string pac { get; set; }
        public string sch { get; set; }
        public string slu { get; set; }
        public string sta { get; set; }
        public string stn { get; set; }
        public string tac { get; set; }
        public string tcc { get; set; }
        public string ton { get; set; }
        public string via { get; set; }
        public string way { get; set; }
        public string cc { get; set; }
        public string hs { get; set; }
        public string ne { get; set; }
        public string nw { get; set; }
        public string rd { get; set; }
        public string se { get; set; }
        public string sr { get; set; }
        public string st { get; set; }
        public string sw { get; set; }
        public string tc { get; set; }
        public string to { get; set; }
        public string ts { get; set; }
        public string up { get; set; }
        public string uw { get; set; }
        public string va { get; set; }
    }
}
